parameters:
    ezpublish.signalslot.service.content.class: SQLI\EzToolboxBundle\Services\Core\ContentService

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $logDir: "%kernel.logs_dir%"
            $adminLoggerEnabled: "%sqli_ez_toolbox.admin_logger.enabled%"

    eZ\Publish\Core\Helper\TranslationHelper: '@ezpublish.translation_helper'
    eZ\Publish\Core\Helper\FieldHelper: '@ezpublish.field_helper'
    eZ\Publish\Core\MVC\Symfony\View\ViewManagerInterface: '@ezpublish.view_manager'
    eZ\Publish\Core\MVC\Symfony\Templating\Twig\Extension\ContentExtension: '@ezpublish.twig.extension.content'

    SQLI\EzToolboxBundle\Command\:
        resource: "../../Command/*"

    SQLI\EzToolboxBundle\Controller\:
        resource: "../../Controller/*"
        exclude: "../../Controller/{Controller}"

    SQLI\EzToolboxBundle\Form\:
        resource: "../../Form/*"

    SQLI\EzToolboxBundle\Services\:
        resource: '../../Services/*'

    SQLI\EzToolboxBundle\Services\Twig\:
        resource: '../../Services/Twig/*'
        tags:
            - { name: twig.extension }

    SQLI\EzToolboxBundle\QueryType\:
        resource: ../../QueryType/
        tags:
            - { name: ezpublish.query_type }

    SQLI\EzToolboxBundle\Annotations\SQLIAnnotationManager:
        arguments:
            - "Entity"
            - "%sqli_ez_toolbox.entities%"
            - "%kernel.project_dir%"
            - "@annotation_reader"


    # Handler Parameters
    SQLI\EzToolboxBundle\Services\Parameter\ParameterHandlerMaintenance:
        tags:
            - { name: sqli.parameter_handler }